---
language: node_js
dist: xenial
os: linux

cache:
  directories:
    - $HOME/cache

jobs:
  include:
    # TODO(iphydf): Enable this once node 14 isn't broken.
    #- node_js: "node"
    - node_js: "13"
      env: CHECK_FORMAT=true
    - node_js: "12"
      if: type IN (push, api, cron)
    - node_js: "11"
      if: type IN (push, api, cron)
    - node_js: "10"

addons:
  apt:
    packages:
      - libopus-dev
      - libvpx-dev

before_script:
  - export CACHE_DIR="$HOME/cache"
  - export CFLAGS="-I$CACHE_DIR/usr/include -O3"
  - export LDFLAGS="-L$CACHE_DIR/usr/lib"
  - export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
  - export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
  - tools/install-deps.sh > /dev/null

script:
  - npm run doc
  - npm run test
  - npm run report-coverage
  - if [ "$CHECK_FORMAT" = true ]; then npm run format && git diff --exit-code; fi

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
